version: '3.4'

services:
  database:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=NichoShopDB
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data/ 

  cache:
    image: redis
    container_name: cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_cache:/data

volumes:
  postgres_db:
  redis_cache: