/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Form: typeof import('@primevue/forms/form')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Index: typeof import('./src/components/home/Index.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    Order: typeof import('./src/components/home/Order.vue')['default']
    Password: typeof import('primevue/password')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/common/Search.vue')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    SvgIcon: typeof import('./src/components/common/SvgIcon.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
